services:
  django:
    build: .
    # image: luishmc/pmodularc-django:latest
    ports:
      - "80:8000"
    # volumes:
    #   - .:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always