# Generated by Django 5.0.2 on 2024-08-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_codigoseguridad_codigo_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoseguridad',
            name='expira_en',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='codigoseguridad',
            name='utilizado',
            field=models.BooleanField(default=False),
        ),
    ]
