# Generated by Django 5.0.2 on 2024-08-04 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_codigoseguridad_expira_en_codigoseguridad_utilizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigoseguridad',
            name='expira_en',
        ),
    ]
