# Generated by Django 5.0.2 on 2024-08-04 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_codigoseguridad_expira_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigoseguridad',
            name='utilizado',
        ),
    ]
