# Generated by Django 5.0.2 on 2024-08-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_codigoseguridad_utilizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fecha_baneo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
