# Generated by Django 5.0.2 on 2024-08-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_problemaencurso_id_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemaencurso',
            name='comentario_completado',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
