# Generated by Django 5.0.2 on 2024-09-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_problemaencurso_comentario_completado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='letra_edificio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
